### ISSUE TITLE
[AMQP] Doesn't work with Akka.Streams v.1.3.6  and higher

### ISSUE THREAD

**Issue by Larsus** [akkadotnet/Alpakka#60]
```
Method not found: 'Void Akka.Streams.Stage.GraphStageLogic.SetHandler(Akka.Streams.Outlet, System.Action, System.Action)'.

   at Akka.Streams.Amqp.AmqpSourceStage.AmqpSourceStageLogic..ctor(AmqpSourceStage stage)
   at Akka.Streams.Amqp.AmqpSourceStage.CreateLogic(Attributes inheritedAttributes)
   at Akka.Streams.Stage.GraphStage`1.CreateLogicAndMaterializedValue(Attributes inheritedAttributes)
   at Akka.Streams.Implementation.Fusing.GraphAssembly.Materialize(Attributes inheritedAttributes, IModule[] copiedModules, IDictionary`2 materializedValues, Action`1 register)
   at Akka.Streams.Implementation.ActorMaterializerImpl.ActorMaterializerSession.MaterializeGraph(GraphModule graph, Attributes effectiveAttributes, IDictionary`2 materializedValues)
   at Akka.Streams.Implementation.ActorMaterializerImpl.ActorMaterializerSession.MaterializeAtomic(AtomicModule atomic, Attributes effectiveAttributes, IDictionary`2 materializedValues)
   at Akka.Streams.Implementation.MaterializerSession.MaterializeModule(IModule module, Attributes effectiveAttributes)
   at Akka.Streams.Implementation.MaterializerSession.Materialize()
   at Akka.Streams.Implementation.ActorMaterializerImpl.Materialize[TMat](IGraph`2 runnable, Func`2 subFlowFuser, Attributes initialAttributes)
   at Akka.Streams.Implementation.ActorMaterializerImpl.Materialize[TMat](IGraph`2 runnable)
   at Akka.Streams.Dsl.RunnableGraph`1.Run(IMaterializer materializer)
   at Akka.Streams.Dsl.Source`2.RunWith[TMat2](IGraph`2 sink, IMaterializer materializer)
```

It looks like you have not update the nuget package after changes:
[pr 32](https://github.com/akkadotnet/Alpakka/pull/35)
[pr 56](https://github.com/akkadotnet/Alpakka/pull/56)

**Comment by Arkatufus** [comment]
We're overhauling Alpakka right now, this should be fixed in the current dev branch.
